"""Runtime guards for the shipped Docker stack (anti-drift).

Both invariants here encode bugs that made a freshly scaffolded
``docker-compose up`` unhealthy, and that no existing test caught because they
only surface at container runtime:

1. **BAML client version sync** — the checked-in ``baml_client/`` must be
   generated by the same version that ``generators.baml`` declares and that the
   runtime dependency pins. The Dockerfiles regenerate the client in-image, but
   compose bind-mounts the source tree over ``/app``, so a stale checked-in
   client shadows the fresh one and the API dies at import with
   "baml-py is likely out of date". v0.3.5 bumped ``generators.baml`` and the
   pin but left the client stale, which is exactly this drift.

2. **Frontend healthcheck must use IPv4** — ``nginx.conf`` listens on IPv4 only
   (``listen 80;``), so a healthcheck against ``localhost`` resolves to ``::1``
   and fails forever while nginx serves correctly.
"""

import re
from pathlib import Path

import pytest

_TEMPLATES = Path(__file__).resolve().parent.parent / "project_initializer"

_FASTAPI_API = _TEMPLATES / "templates-api-fastapi" / "api"
_NESTJS_API = _TEMPLATES / "templates-api-nestjs" / "api"
_FRONTEND_DOCKERFILE = _TEMPLATES / "templates" / "frontend" / "Dockerfile"


def _generators_version(api_dir: Path) -> str:
    """Return the version declared in the template's baml_src/generators.baml."""
    text = (api_dir / "baml_src" / "generators.baml").read_text(encoding="utf-8")
    match = re.search(r'version\s+"([^"]+)"', text)
    assert match, f"no version declared in {api_dir}/baml_src/generators.baml"
    return match.group(1)


@pytest.mark.unit
def test_fastapi_baml_client_matches_generator_and_pin():
    """The FastAPI baml_client, generators.baml, and baml-py pin must agree."""
    declared = _generators_version(_FASTAPI_API)

    client = (_FASTAPI_API / "baml_client" / "__init__.py").read_text(encoding="utf-8")
    client_match = re.search(r'__version__ = "([^"]+)"', client)
    assert client_match, "no __version__ in the checked-in FastAPI baml_client"

    requirements = (_FASTAPI_API / "requirements.txt").read_text(encoding="utf-8")
    pin_match = re.search(r"^baml-py==(.+)$", requirements, re.MULTILINE)
    assert pin_match, "baml-py is not pinned in the FastAPI requirements.txt"

    assert client_match.group(1) == declared, (
        f"checked-in baml_client was generated by {client_match.group(1)} but "
        f"generators.baml declares {declared} — regenerate with `baml-cli generate`"
    )
    assert pin_match.group(1) == declared, (
        f"baml-py is pinned to {pin_match.group(1)} but generators.baml declares {declared}"
    )


@pytest.mark.unit
def test_nestjs_baml_client_matches_generator_and_pin():
    """The NestJS baml_client, generators.baml, and @boundaryml/baml pin must agree."""
    declared = _generators_version(_NESTJS_API)

    client = (_NESTJS_API / "baml_client" / "index.ts").read_text(encoding="utf-8")
    client_match = re.search(r'export const version = "([^"]+)"', client)
    assert client_match, "no exported version in the checked-in NestJS baml_client"

    package_json = (_NESTJS_API / "package.json").read_text(encoding="utf-8")
    pin_match = re.search(r'"@boundaryml/baml":\s*"([^"]+)"', package_json)
    assert pin_match, "@boundaryml/baml is not pinned in the NestJS package.json"

    assert client_match.group(1) == declared, (
        f"checked-in baml_client was generated by {client_match.group(1)} but "
        f"generators.baml declares {declared} — regenerate with `npx baml-cli generate`"
    )
    assert pin_match.group(1) == declared, (
        f"@boundaryml/baml is pinned to {pin_match.group(1)} but "
        f"generators.baml declares {declared}"
    )


@pytest.mark.unit
def test_frontend_healthcheck_targets_ipv4():
    """The frontend HEALTHCHECK must not use localhost — nginx is IPv4-only."""
    dockerfile = _FRONTEND_DOCKERFILE.read_text(encoding="utf-8")
    healthcheck = [
        line for line in dockerfile.splitlines() if "wget" in line and "/health" in line
    ]
    assert healthcheck, "no wget-based HEALTHCHECK found in the frontend Dockerfile"

    for line in healthcheck:
        assert "//localhost" not in line, (
            "frontend HEALTHCHECK targets localhost, which resolves to ::1 while "
            "nginx.conf listens on IPv4 only — the container would report unhealthy "
            "forever. Use 127.0.0.1."
        )
        assert "//127.0.0.1" in line, f"expected an IPv4 healthcheck target, got: {line}"


@pytest.mark.unit
@pytest.mark.parametrize("framework", ["fastapi", "nestjs"])
def test_nginx_listens_ipv4_only_justifying_the_healthcheck(framework):
    """Pin the assumption the healthcheck guard rests on: nginx binds IPv4 only.

    If a future change adds `listen [::]:80;`, this fails as a prompt to revisit
    the healthcheck guard above rather than leave a stale rationale behind.
    """
    nginx_conf = _TEMPLATES / f"templates-api-{framework}" / "frontend" / "nginx.conf"
    text = nginx_conf.read_text(encoding="utf-8")
    assert "listen 80;" in text
    assert "listen [::]:80" not in text
