import { LUCIDE_ICONS, LucideIconProvider } from 'lucide-angular';
import {
  ArrowLeft,
  ArrowUp,
  Bell,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronUp,
  CircleAlert,
  CircleCheckBig,
  CircleX,
  Copy,
  EllipsisVertical,
  Eye,
  EyeOff,
  House,
  Inbox,
  Info,
  LayoutDashboard,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  Menu,
  MessageSquare,
  Minus,
  Monitor,
  Moon,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Plus,
  Search,
  Settings,
  Settings2,
  SlidersVertical,
  SquareFunction,
  Sun,
  SunMoon,
  Trash2,
  TriangleAlert,
  User,
  X,
} from 'lucide-angular';

// LucideIconProvider matches template names by converting kebab-case to PascalCase
// and looking up the result in this map's keys. Most entries use the icon's own
// PascalCase identifier as the key; the aliased entries below map the deprecated
// names (CheckCircle, Sliders, FunctionSquare, Home, Loader2) to their canonical
// (non-deprecated) counterparts in lucide-angular ≥ 0.477.
//
// Inside Material buttons, add `matButtonIcon` to the <lucide-icon> and pass
// [size]="18"; icon buttons size any inner svg to 24px on their own.
const icons = {
  ArrowLeft,
  ArrowUp,
  Bell,
  Check,
  CheckCircle: CircleCheckBig,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronUp,
  CircleAlert,
  CircleCheckBig,
  CircleX,
  Copy,
  EllipsisVertical,
  Eye,
  EyeOff,
  FunctionSquare: SquareFunction,
  Home: House,
  Inbox,
  Info,
  LayoutDashboard,
  Loader2: LoaderCircle,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  Menu,
  MessageSquare,
  Minus,
  Monitor,
  Moon,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Plus,
  Search,
  Settings,
  Settings2,
  Sliders: SlidersVertical,
  Sun,
  SunMoon,
  Trash2,
  TriangleAlert,
  User,
  X,
};

export type IconName = keyof typeof icons;

export const ICON_PROVIDER = {
  provide: LUCIDE_ICONS,
  multi: true,
  useValue: new LucideIconProvider(icons),
};
